name: Build on Linux

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        shell: bash -l {0}
        run: |
          make tetgen --directory src
          mv src/tetgen tetgen-${{ runner.os }}

      - name: Test
        shell: bash -l {0}
        run: |
          ./tetgen-${{ runner.os }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: tetgen-${{ runner.os }}
          path: tetgen-${{ runner.os }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tetgen-${{ runner.os }}
      


