name: Build on Windows

on: push

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        shell: pwsh
        run: |
          cd src
          ./make_win.PS1
          cd ..
          mv src/tetgen.exe tetgen.exe
          Compress-Archive src/, tetgen.exe tetgen-${{ runner.os }}.zip

      - name: Test
        shell: pwsh
        run: |
          ./tetgen.exe

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: tetgen-${{ runner.os }}.zip
          path: tetgen-${{ runner.os }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tetgen-${{ runner.os }}.zip