name: Build on Mac/Linux

on: push

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        shell: bash -l {0}
        run: |
          make tetgen --directory src
          mv src/tetgen tetgen
          zip tetgen-${{ runner.os }} tetgen src/*

      - name: Test
        shell: bash -l {0}
        run: |
          ./tetgen

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: tetgen-${{ runner.os }}.zip
          path: tetgen-${{ runner.os }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tetgen-${{ runner.os }}.zip
      


